apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: cleanup-completed-jobs
  namespace: development
spec:
  rules:
    - name: cleanup-jobs
      match:
        resources:
          kinds:
            - Job
      mutate:
        patchStrategicMerge:
          spec:
            ttlSecondsAfterFinished: 60
